name: xarleta_financas

description: Controle financeiro pessoal offline, leve e privado.

publish_to: "none"

version: 2.0.0+7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  local_auth: ^2.3.0
  csv: ^6.0.0
  fl_chart: ^0.69.0
  share_plus: ^10.1.4
  file_picker: ^8.1.7
  sqflite_common_ffi: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true